export const tavernTalkData = [
  {
    handle: `@GandalfTheGrey 🧙‍♂️`,
    profilePic: `images/gandalf.jpg`,
    likes: 452,
    retweets: 123,
    tweetText: `A wizard is never late, nor is he early. He arrives precisely when he means to.`,
    replies: [
      {
        handle: `@FrodoBaggins 🧝‍♂️`,
        profilePic: `images/frodo-baggins.jpg`,
        tweetText: `You were late though. We all saw it. 😅`,
      },
      {
        handle: `@SarumanTheWhite ⚪`,
        profilePic: `images/sarum.jpg`,
        tweetText: `Classic Gandalf. Always dramatic.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "12345-gandalf-uuid-001",
  },
  {
    handle: `@CriticalHit69 🎯`,
    profilePic: `images/rogue.jpg`,
    likes: 89,
    retweets: 24,
    tweetText: `Just crit a dragon with a sneak attack while invisible. Rogue life = best life.`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "rogue-uuid-4242",
  },
  {
    handle: `@Bard4Life 🎵`,
    profilePic: `images/bard.jpg`,
    likes: 152,
    retweets: 41,
    tweetText: `Just seduced a lich with a power ballad. #Charisma20`,
    replies: [
      {
        handle: `@ClericOfLight ✨`,
        profilePic: `images/cleric.jpg`,
        tweetText: `This is blasphemy.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "bard-seduces-lich-888",
  },
  {
    handle: `@DungeonMaster 👁️‍🗨️`,
    profilePic: `images/dungeon-master.jpg`,
    likes: 320,
    retweets: 112,
    tweetText: `Reminder: Your actions have consequences. Yes, even that nat 1.`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "dm-warning-3141",
  },
];
